--- #YAML:1.0
name:                Continuity-Widget
version:             0.01
abstract:            Handy Moose-based Widget Thingie for Continuity Apps
license:             ~
author:              
    - Brock Wilcox <awwaiid@thelackthereof.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Continuity:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
